version: "3.9"
services:
  hysteria:
    image: tobyxdd/hysteria:latest
    container_name: hysteria
    restart: always
    networks:
      - caddy
    ports:
      - "8443:8443/udp"
    volumes:
      - caddy_data:/etc/letsencrypt:ro
      - /var/log:/var/log:rw
      - /etc/localtime:/etc/localtime:ro
      - ./etc/hysteria.json:/etc/hysteria.json
    environment:
      - LOGGING_LEVEL=warn
    command: [ "server", "--config", "/etc/hysteria.json" ]

volumes:
  caddy_data:
    external: true

networks:
  caddy:
    external: true
