version: "3.9"
services:
    hysteria:
        image: tobyxdd/hysteria:latest
        container_name: hysteria
        restart: always
        cap_add:
            - CAP_NET_BIND_SERVICE
        volumes:
            - caddy_data:/etc/letsencrypt:ro
            - /var/log:/var/log:rw
            - $HOME/Docker/hysteria/etc/hysteria.json:/etc/hysteria.json
        environment:
            - TZ=UTC
            - LOGGING_LEVEL=debug
        command: [ "server", "--config", "/etc/hysteria.json" ]

volumes:
    caddy_data:
        external: true
