version: "3.9"
services:
  caddy:
    image: caddy
    container_name: caddy
    restart: always
    cap_add:
      - CAP_NET_BIND_SERVICE
    networks:
      - caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - data:/data
      - config:/config
      - sockets:/dev/shm
      - /var/log:/var/log
      - /etc/localtime:/etc/localtime:ro
      - ./html:/var/www/html
      - ./clients:/var/www/clients
      - ./etc/caddy.json:/etc/caddy/caddy.json
    command: caddy run --config /etc/caddy/caddy.json

volumes:
  data:
  config:
  sockets:
    external: true

networks:
  caddy:
    external: true
