version: "3.9"
services:
  mtprotopy:
    container_name: mtprotopy
    image: mtprotopy
    restart: always
    networks:
      - caddy
    expose:
      - "5443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/config.toml:/config/config.toml:ro
      - $HOME/Rainb0w_Home/rainb0w_users.toml:/config/users.toml:rw
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "10m"

networks:
  caddy:
    external: true
