version: "3.9"

services:
  blocky:
    image: spx01/blocky:latest
    restart: always
    container_name: blocky
    user: 0:0
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    networks:
      caddy:
        ipv4_address: 172.18.0.53
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "853:853/udp"
    expose:
      - "4343"
    environment:
      - TZ=UTC
    volumes:
      - caddy_data:/etc/letsencrypt:ro
      - /var/log:/logs
      - ./etc/config.yml:/app/config.yml

volumes:
  caddy_data:
    external: true

networks:
  caddy:
    external: true
